version: '3'

services:
  web:
    build:
      #from where to build the dockerfile from
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #do not make a reference for the node_modules
      - .:/app # map the current directory to the container dir